stages:
  - test
  - release

test-calibr8-py37:
  stage: test
  image: python:3.7
  script:
    - pip install -e . && pip install pytest pytest-cov
    - pytest --cov=./calibr8 --cov-append --cov-report term-missing calibr8/tests.py
    - pip install "pymc3>=3.11.2,<4"
    - pip install pygmo
    - pytest --cov=./calibr8 --cov-append --cov-report term-missing calibr8/tests.py
    - coverage report -m

test-calibr8-py38:
  stage: test
  image: python:3.8
  script:
    - pip install -e . && pip install pytest pytest-cov
    - pytest --cov=./calibr8 --cov-append --cov-report term-missing calibr8/tests.py
    - pip install aesara && pytest --cov=./calibr8 --cov-append --cov-report term-missing calibr8/tests.py && pip uninstall aesara -y
    - pip install "theano-pymc==1.1.2" && pytest --cov=./calibr8 --cov-append --cov-report term-missing calibr8/tests.py && pip uninstall theano-pymc -y
    - pip install "pymc3>=3.11.2,<4"
    - pip install pygmo
    - pytest --cov=./calibr8 --cov-append --cov-report term-missing calibr8/tests.py
    - coverage report -m

release-calibr8:
  stage: release
  image: python:3.7
  script:
    - python setup.py bdist_wheel && cp dist/*.whl .
  artifacts:
    paths:
      - ./*.whl
    expire_in: 30 yrs
  only:
    # only run on refs that are named like v1.2 or v1.2.3
    - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
